# General material models

In [1]:
from sigmaepsilon.solid.material.utils import HMH_M_v
import numpy as np
HMH_M_v(*(np.random.rand(10),)*3).shape

(10,)

In [2]:
import numpy as np

from sigmaepsilon.solid.material import ElasticityTensor
from sigmaepsilon.math.linalg import ReferenceFrame
from sigmaepsilon.solid.material.utils import elastic_stiffness_matrix
from sigmaepsilon.math.logical import isposdef, issymmetric

# create a material stiffness matrix in the 123 frame, which is bound
# to the anatomical directions of the material
hooke = elastic_stiffness_matrix(E=210000, NU=0.3)
yield_strength=355.0

assert isposdef(hooke)
assert issymmetric(hooke, 1e-8)

# create a 4d tensor from this matrix and check if the 2d representation of it
# coincides with the matrix
frame = ReferenceFrame(dim=3)
tensor = ElasticityTensor(hooke, frame=frame, tensorial=False, yield_strength=yield_strength)

In [3]:
tensor.yield_strength

355.0

In [4]:
tensor.calculate_strains(np.array([yield_strength, 0.0, 0.0, 0.0, 0.0, 0.0]))

array([ 0.00169048, -0.00050714, -0.00050714,  0.        ,  0.        ,
        0.        ])

In [5]:
tensor.calculate_equivalent_stress(np.array([0.002, 0.0, 0.0, 0.0, 0.0, 0.0]))

323.0769230769232

In [6]:
tensor.calculate_equivalent_stress(np.array([0.0, 0.002, 0.0, 0.0, 0.0, 0.0]))

323.0769230769231

In [7]:
s11, s22, s33, s23, s13, s12 = (2*np.random.rand(10)/1000 for _ in range(6))
tensor.calculate_equivalent_stress(s11, s22, s33, s23, s13, s12)

array([312.45342707, 242.72187927, 296.71784759, 327.42713959,
       356.31328107, 373.34254145, 336.65311252, 240.993593  ,
       394.24392753, 411.41149212])

In [8]:
tensor.utilization(s11, s22, s33, s23, s13, s12) * 100

array([ 88.01504988,  68.37236036,  83.58249228,  92.23299707,
       100.36993833, 105.16691308,  94.83186268,  67.88551916,
       111.05462747, 115.89056116])

In [9]:
tensor.calculate_stresses(np.random.rand(6)).shape

(6,)

In [10]:
tensor.calculate_stresses(np.random.rand(10, 6)).shape

(10, 6)

In [11]:
strains = tensor.calculate_strains(np.array([yield_strength, 0.0, 0.0, 0.0, 0.0, 0.0]))
tensor.utilization(strains) * 100

100.00000000000003

In [12]:
strains = tensor.calculate_strains(np.eye(6) * yield_strength)
tensor.utilization(strains) * 100

array([100.        , 100.        , 100.        , 173.20508076,
       173.20508076, 173.20508076])

In [13]:
strains = tensor.calculate_strains(np.array([10*yield_strength, 10*yield_strength, 10*yield_strength, 0.0, 0.0, 0.0]))
tensor.utilization(strains) * 100

2.561956906402615e-13

Utilization for a single state of strain:

In [14]:
strains = 2*np.random.rand(6)/1000
strains

array([0.00119028, 0.00021427, 0.00175297, 0.00120275, 0.00123302,
       0.00046032])

In [15]:
tensor.utilization(strains) * 100

93.28330739855922

Utilizations for several states with bulk evaluation:

In [16]:
tensor.utilization(2*np.random.rand(10, 6)/1000) * 100

array([120.20683049,  73.71647629,  97.61521405, 115.32607562,
        75.12146724, 107.60671741,  83.0931512 ,  83.78853228,
       115.27364126,  50.4835455 ])

In [17]:
tensor.utilization(2*np.random.rand(10, 6)/1000).shape

(10,)

In [18]:
tensor.utilization(*(2*np.random.rand(10)/1000 for _ in range(6))) * 100

array([ 80.75826586, 124.80532675,  63.42834865,  96.30484824,
        79.85557091,  76.30290992,  94.02298408,  58.98226608,
        83.70141049,  42.1667663 ])

In [19]:
tensor.utilization(*(2*np.random.rand(10)/1000 for _ in range(6))).shape

(10,)